server:
  port: 8080

spring:
  application:
    name: STORE-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
   
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store_db
    username: root
    password: Root@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
